Link to dataset : https://drive.google.com/file/d/1sbQ5WJ-KCPBrhT2YagtaARGoujCMpB8Q/view

# SA-2025 WEEK 3 GRADED ASSIGNMENT

> Spaceship Titanic

Predict which passengers are transported to an alternate dimension

![](https://www.gannett-cdn.com/-mm-/682bf77435754aee88576469063388a7d8b07c2a/c=0-150-1280-873/local/-/media/2017/02/01/Reno/RGJ/636215634914521096-image001.jpg?width=660&height=373&fit=crop&format=pjpg&auto=webp)

### <b>Description</b>

Welcome to the year 2912, where your data science skills are needed to solve a cosmic mystery. We've received a transmission from four lightyears away and things aren't looking good.

The Spaceship Titanic was an interstellar passenger liner launched a month ago. With almost 13,000 passengers on board, the vessel set out on its maiden voyage transporting emigrants from our solar system to three newly habitable exoplanets orbiting nearby stars.

While rounding Alpha Centauri en route to its first destination—the torrid 55 Cancri E—the unwary Spaceship Titanic collided with a spacetime anomaly hidden within a dust cloud. Sadly, it met a similar fate as its namesake from 1000 years before. Though the ship stayed intact, almost half of the passengers were transported to an alternate dimension!

### <b>Data description</b>

- Personal records for about two-thirds (~8700) of the passengers, to be used as training data.
- <code>PassengerId</code> - A unique Id for each passenger. Each Id takes the form gggg_pp where gggg indicates a group the passenger is travelling with and pp is their number within the group. People in a group are often family members, but not always.
- <code>HomePlanet</code> - The planet the passenger departed from, typically their planet of permanent residence.
- <code>CryoSleep</code> - Indicates whether the passenger elected to be put into suspended animation for the duration of the voyage. Passengers in cryosleep are confined to their cabins.
- <code>Cabin</code> - The cabin number where the passenger is staying. Takes the form deck/num/side, where side can be either P for Port or S for Starboard.
- <code>Destination</code> - The planet the passenger will be debarking to.
- <code>Age</code> - The age of the passenger.
- <code>VIP</code> - Whether the passenger has paid for special VIP service during the voyage.
- <code>RoomService, FoodCourt, ShoppingMall, Spa, VRDeck</code> - Amount the passenger has billed at each of the Spaceship Titanic's many luxury amenities.
- <code>Name</code> - The first and last names of the passenger.
- <code>Transported</code> - Whether the passenger was transported to another dimension. This is the target, the column you are trying to predict.

### <b>Algorithm Documentation</b> (Highly recommended!)
- <code>Logistic Regression</code> : https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
- <code>SVM</code> : https://scikit-learn.org/stable/modules/svm.html
Confusion Matrix : https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html
- <code>Plot Confusion Matrix</code> : https://scikit-learn.org/stable/modules/generated/sklearn.metrics.plot_confusion_matrix.html
- <code>ROC_AUC Score</code> : https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_auc_score.html#sklearn.metrics.roc_auc_score
- <code>Classification Report</code> : https://scikit-learn.org/stable/modules/generated/sklearn.metrics.classification_report.html
- <code>Label Encoder</code> : https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html
- <code>Label Binarizer</code> : https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelBinarizer.html
- <code>Standard Scaler</code> : https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html
- <code>Cross Val Score</code> : https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html

# <span><h1 style = "font-family: garamond; font-size: 40px; font-style: normal; letter-spcaing: 3px; background-color: #f6f5f5; color :#fe346e; border-radius: 100px 100px; text-align:center">Install Required Libraries</h1></span>

In [26]:
!pip install --upgrade scikit-learn  #There was an error with importing confusion_matrix from sklearn.mertices , so there was a need to upgrade it for google colab
# even after upgrading the plot_confusion_matrix didnt worked as it has been changed in new version

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [27]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

#### Read the data

In [28]:
import pandas as pd


file_id = '1sbQ5WJ-KCPBrhT2YagtaARGoujCMpB8Q'

# 2. Create the direct download URL
direct_url = "https://drive.google.com/uc?id=1sbQ5WJ-KCPBrhT2YagtaARGoujCMpB8Q"
df = pd.read_csv(direct_url)
print(df.head())

  PassengerId HomePlanet  CryoSleep  Cabin Destination  Age    VIP  \
0     0001_01     Europa      False  B/0/P   Andromeda   39  False
1     0002_01      Earth      False  F/0/S   Andromeda   24  False
2     0003_01     Europa      False  A/0/S   Andromeda   58   True
3     0003_02     Europa      False  A/0/S   Andromeda   33  False
4     0004_01      Earth      False  F/1/S   Andromeda   16  False

   RoomService  FoodCourt  ShoppingMall   Spa  VRDeck               Name  \
0            0          0             0     0       0    Maham Ofracculy
1          109          9            25   549      44       Juanna Vines
2           43       3576             0  6715      49      Altark Susent
3            0       1283           371  3329     193       Solam Susent
4          303         70           151   565       2  Willy Santantines

   Transported
0        False
1         True
2        False
3        False
4         True

#### Check the shape of data. It should be  (8693, 14)

In [29]:
df.shape

(8693, 14)

#### Apply describe on dataframe

In [30]:
df.describe()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,8693.000000,8693.000000,8693.000000,8693.000000,8693.000000,8693.000000
mean,28.728517,220.009318,448.434027,169.572300,304.588865,298.261820
std,14.355438,660.519050,1595.790627,598.007164,1125.562559,1134.126417
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,20.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,37.000000,41.000000,61.000000,22.000000,53.000000,40.000000
max,79.000000,14327.000000,29813.000000,23492.000000,22408.000000,24133.000000

#### Check if there any null value in the dataset.

In [31]:
df.isnull().sum()

PassengerId     0
HomePlanet      0
CryoSleep       0
Cabin           0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Name            0
Transported     0
dtype: int64

#### Number continuous and categorical features

In [32]:
#################################################################

# Don't make mistake here. Ask in the discussion section if you are stuck. Help will be provided....
continuous_features=df.select_dtypes(include=["int64","float"])
categorical_features=df.select_dtypes(include=["object"])
print(f"continuous_fet:{continuous_features}")
print(f"categorical_features:{categorical_features}")

continuous_fet:      Age  RoomService  FoodCourt  ShoppingMall   Spa  VRDeck
0      39            0          0             0     0       0
1      24          109          9            25   549      44
2      58           43       3576             0  6715      49
3      33            0       1283           371  3329     193
4      16          303         70           151   565       2
...   ...          ...        ...           ...   ...     ...
8688   41            0       6819             0  1643      74
8689   18            0          0             0     0       0
8690   26            0          0          1872     1       0
8691   32            0       1049             0   353    3235
8692   44          126       4688             0     0      12

[8693 rows x 6 columns]
categorical_features:     PassengerId HomePlanet     Cabin Destination               Name
0        0001_01     Europa     B/0/P   Andromeda    Maham Ofracculy
1        0002_01      Earth     F/0/S   Andromeda       Juanna Vines
2        0003_01     Europa     A/0/S   Andromeda      Altark Susent
3        0003_02     Europa     A/0/S   Andromeda       Solam Susent
4        0004_01      Earth     F/1/S   Andromeda  Willy Santantines
...          ...        ...       ...         ...                ...
8688     9276_01     Europa    A/98/P       Virgo  Gravior Noxnuther
8689     9278_01      Earth  G/1499/S      Cygnus    Kurta Mondalley
8690     9279_01      Earth  G/1500/S   Andromeda       Fayey Connon
8691     9280_01     Europa   E/608/S       Virgo   Celeon Hontichre
8692     9280_02     Europa   E/608/S   Andromeda   Propsh Hontichre

[8693 rows x 5 columns]

#### Unique values

In [33]:
# Print the number of unique values of the categorical features
categorical_features.nunique()

# seeing the n-unique for passengerID , we can say there is no error and no overlap in passengerID as all are unique .
# But there is an anomaly as Name of passengers might overlap as not all of them are unique .

PassengerId    8693
HomePlanet        3
Cabin          6560
Destination       3
Name           8473
dtype: int64

<code>Note: If we apply one-hot-encoding to a categorical feature with many unique values, </code>
- Number of columns will be high
- Time required for training a model will be high
- We may not get usefull insights about the data

<code>This is the reason we are droping the features with more unique values.</code>

#### Drop the features

In [34]:
# Drop those categorical features which have more than 25 unique values
df1=df.drop(columns=["PassengerId","Cabin","Name"],axis=1)
df1
# Print the shape after droping the features
df1.shape
# Check: Shape --> (8693, 11)

## ======== YOUR CODE HERE ======== ##

df1
## ======== YOUR CODE HERE ======== ##

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,Europa,False,Andromeda,39,False,0,0,0,0,0,False
1,Earth,False,Andromeda,24,False,109,9,25,549,44,True
2,Europa,False,Andromeda,58,True,43,3576,0,6715,49,False
3,Europa,False,Andromeda,33,False,0,1283,371,3329,193,False
4,Earth,False,Andromeda,16,False,303,70,151,565,2,True
...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,False,Virgo,41,True,0,6819,0,1643,74,False
8689,Earth,True,Cygnus,18,False,0,0,0,0,0,False
8690,Earth,False,Andromeda,26,False,0,0,1872,1,0,True
8691,Europa,False,Virgo,32,False,0,1049,0,353,3235,False
8692,Europa,False,Andromeda,44,False,126,4688,0,0,12,True

#### One Hot Encoding

In [35]:
# Hint: search for get_dummies

df2=pd.get_dummies(df1,columns=["HomePlanet","Destination"],dtype=int,drop_first=True)

# Check: Shape --> (8693, 15)
df2

,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,HomePlanet_Europa,HomePlanet_Mars,Destination_Cygnus,Destination_Virgo
0,False,39,False,0,0,0,0,0,False,1,0,0,0
1,False,24,False,109,9,25,549,44,True,0,0,0,0
2,False,58,True,43,3576,0,6715,49,False,1,0,0,0
3,False,33,False,0,1283,371,3329,193,False,1,0,0,0
4,False,16,False,303,70,151,565,2,True,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,False,41,True,0,6819,0,1643,74,False,1,0,0,1
8689,True,18,False,0,0,0,0,0,False,0,0,1,0
8690,False,26,False,0,0,1872,1,0,True,0,0,0,0
8691,False,32,False,0,1049,0,353,3235,False,1,0,0,1
8692,False,44,False,126,4688,0,0,12,True,1,0,0,0

#### Changing bool columns to 0,1

In [36]:
df2=df2.replace({True:1,False:0})
df2

/tmp/ipykernel_3563/438465171.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2=df2.replace({True:1,False:0})

,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,HomePlanet_Europa,HomePlanet_Mars,Destination_Cygnus,Destination_Virgo
0,0,39,0,0,0,0,0,0,0,1,0,0,0
1,0,24,0,109,9,25,549,44,1,0,0,0,0
2,0,58,1,43,3576,0,6715,49,0,1,0,0,0
3,0,33,0,0,1283,371,3329,193,0,1,0,0,0
4,0,16,0,303,70,151,565,2,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,0,41,1,0,6819,0,1643,74,0,1,0,0,1
8689,1,18,0,0,0,0,0,0,0,0,0,1,0
8690,0,26,0,0,0,1872,1,0,1,0,0,0,0
8691,0,32,0,0,1049,0,353,3235,0,1,0,0,1
8692,0,44,0,126,4688,0,0,12,1,1,0,0,0

#### Split the data into train and test

In [37]:

X=df2.drop(columns=["Transported"],axis=1)
y=df2["Transported"]
## Test size should be 15% of the full dataset and use random state = 2022
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.15,random_state=2022
                                               )
## ================================ ##

#### Scale the data using Standard Scaler

In [41]:
## Use Standard Scaler to scale the train and test data
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)


## ======== YOUR CODE HERE ======== ##


## ================================ ##

## <b>Logistic Regression</b>
#### Use default parameters unless mentioned

In [44]:
## Use Random state = 2021 and fit the LR model
model=LogisticRegression(random_state=2021)
model.fit(X_train_scaled,y_train)
## ======== YOUR CODE HERE ======== ##
y_predict=model.predict(X_test_scaled)
## ================================ ##

#### Plot confusion matrix

In [45]:
from  sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_predict))

[[512 125]
 [143 524]]

#### Print classification report

In [52]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.78      0.80      0.79       637
           1       0.81      0.79      0.80       667

    accuracy                           0.79      1304
   macro avg       0.79      0.79      0.79      1304
weighted avg       0.79      0.79      0.79      1304

#### Print accuracy score

In [55]:
from sklearn.metrics import accuracy_score
print(f"accuracy_score:{accuracy_score(y_test,y_predict)}")

accuracy_score:0.7944785276073619

#### Print ROC-AUC score

In [ ]:
## ======== YOUR CODE HERE ======== ##

## Note: Use predict_proba!!! Read documentation/google it


## ================================ ##

#### Plot ROC-AUC Curve

In [ ]:
## ======== YOUR CODE HERE ======== ##

## Set appropriate X label, Y label and Title for the graph


## ================================ ##

#### Cross validation

## <b>SVM</b>
#### Use default parameters unless mentioned

In [ ]:
## ======== YOUR CODE HERE ======== ##


## ================================ ##

#### Plot confusion matrix

In [ ]:
## ======== YOUR CODE HERE ======== ##

## Use display labels as per your choice.


## ================================ ##

#### Print classification report

In [ ]:
## ======== YOUR CODE HERE ======== ##


## ================================ ##

#### Print accuracy score

In [ ]:
## ======== YOUR CODE HERE ======== ##


## ================================ ##

#### Print ROC-AUC score

In [ ]:
## ======== YOUR CODE HERE ======== ##

## Note: Use predict_proba!!! Read documentation/google it


## ================================ ##

#### Plot ROC-AUC curve

In [ ]:
## ======== YOUR CODE HERE ======== ##

## Set appropriate X label, Y label and Title for the graph


## ================================ ##

#### Cross validation

In [ ]:
## ======== YOUR CODE HERE ======== ##

## cv=5



## ================================ ##

# Congratulations! Assignment Completed!