### 1) Import Pandas and Numpy

In [1]:
#your code here
import pandas as pd
import numpy as np

### 2) Import the dataset and  Assign it to a variable called Chipo

#### Import the dataset from
https://github.com/justmarkham/pandas-videos/blob/master/data/chipotle.tsv

#### REMEMBER: It is a .tsv file , you will have to do some research on how to read .tsv files first!

In [ ]:
#your code here
#url="https://github.com/justmarkham/pandas-videos/blob/master/data/chipotle.tsv"
df=pd.read_csv(r"C:\Users\Yash Tripathi\Downloads\chipotle.tsv",sep='\t')
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### 3) See the first 10 entries

In [14]:
#your code here
df.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### 4) What is the number of observations in the dataset?

In [16]:
#your code here
print(df.shape[0])

4622

### 5) What is the number of columns in the dataset?

In [17]:
#your code here
print(len(df.columns))

5

### 6) Print the name of all the columns.

In [18]:
#your code here
df.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

### 7) Which was the most-ordered item?

In [20]:
#your code here
df['quantity'].idxmax()

3598

### 8) For the most-ordered item, how many items were ordered?

In [21]:
#your code here
df['quantity'].max()

15

### 9) What was the most ordered item in the choice_description column?

In [22]:
#your code here
df['choice_description'].value_counts().idxmax()

'[Diet Coke]'

### 10) How many items were ordered in total?

In [28]:
#your code here
df['quantity'].sum()

np.int64(4972)

### 11) Turn the item price into a float

In [31]:
#your code here
df['item_price'] = df['item_price'].apply(lambda x: float(x[1:]) if isinstance(x, str) else x)

# Step 2: Ab data type check karein (yeh float64 dikhayega)
print(df['item_price'].dtype)

float64

### 12) How much was the revenue for the period in the dataset?
#### Revenue will be the sum of quantity * item_price!

In [37]:
#your code 
revenue = (df['quantity'] * df['item_price']).sum()

print(round(revenue, 2))

39237.02

### 13) How many orders were made in the period?

In [38]:
#your code here
df['quantity'].sum()

np.int64(4972)

### 14) What is the average revenue amount per order?

In [39]:
#your code here
print((df['item_price']/df['quantity']).mean())

7.084424491562094

### 15) How many different items are sold?

In [40]:
#your code here
df['item_name'].nunique()

50

### 16) Show a histogram with number of orders with bill on the x-axis.